#exp name and save dir
exp_name: '0306-0053_fbank_81_CNN_LSTM_CTC_Greedy_noOld_ST123'
checkpoint_dir: 'checkpoint/'

#Data
vocab_file: 'units'
train_scp_path: 'data/train/fbank.scp' #fbank,mfcc
train_lab_path: 'data/train/phn_text'
train_trans_path: 'data/train/transcript_phn_text'
valid_scp_path: 'data/dev/fbank.scp' #fbank,mfcc
valid_lab_path: 'data/dev/phn_text'
valid_trans_path: 'data/dev/transcript_phn_text'
left_ctx: 0
right_ctx: 2
n_skip_frame: 2
n_downsample: 2
num_workers: 1
shuffle_train: True
feature_dim: 81 #fbank:81 mfcc:40
output_class_dim: 36
mel: False
feature_type: "fbank"

#Model
rnn_input_size: 243 #feature_dim concat 後面兩個frame 得到81*3=243 fbank:243 mfcc120
rnn_hidden_size: 384
rnn_layers: 4
rnn_type: "nn.LSTM"
bidirectional: True
batch_norm: True
drop_out: 0.2

#CNN
add_cnn: True
layers: 2
channel: "[(1, 32), (32, 32)]"
kernel_size: "[(3, 3), (3, 3)]"
stride: "[(1, 2), (2, 2)]"
padding: "[(1, 1), (1, 1)]"
pooling: "None"
batch_norm: True
activation_function: "relu"

# #[Training]
use_gpu: True
# init_lr: 0.001
# num_epoches: 500
# end_adjust_acc: 2
# lr_decay: 0.5
# batch_size: 64
# weight_decay: 0.0005
# seed: 1234
# verbose_step: 50
# tensorboard_path : './tensorboard/log'

#[test]
decode_dir: 'run'
test_scp_path: 'run/fbank.scp' #fbank,mfcc
test_trans_path: 'transcript_dict.json'
decode_type: "Greedy" #Beam or Greedy
beam_width: 10
lm_alpha: 0
lm_path: 'lm_phone_bg.arpa'

